### ISSUE TITLE
PracticaPrototipo

### ISSUE THREAD

**Issue by ArturoAngonJose** [SistemasTecTlaxiaco/practicaprototipos-equipo-vaii#2]
[PROTOTIPO AXD.pdf](https://github.com/SistemasTecTlaxiaco/practicaprototipos-equipo-vaii/files/6190937/PROTOTIPO.AXD.pdf)

**Comment by Edwin38H** [comment]
calf: 18
falto unas imagenes , unas cuantas lineas en la conclusion y lista de imagenes

**Comment by josealfredo79** [comment]
Bien hecho y revisado
